services:

  spot.broker.legacy:
    image: docker.io/bitnami/kafka:3.7
    container_name: spot.broker.legacy
    hostname: spot.broker.legacy
    restart: "no"
    ports:
      - "9092:9092"
    environment:
      KAFKA_CFG_NODE_ID: 0
      KAFKA_CFG_PROCESS_ROLES: controller,broker
      KAFKA_CFG_CONTROLLER_QUORUM_VOTERS: 0@spot.broker.legacy:19192
      KAFKA_CFG_LISTENERS: "LISTENER_DOCKER_INTERNAL://:19092,CONTROLLER://:19192,LISTENER_DOCKER_EXTERNAL://:9092"
      KAFKA_CFG_ADVERTISED_LISTENERS: "LISTENER_DOCKER_INTERNAL://spot.broker.legacy:19092,LISTENER_DOCKER_EXTERNAL://localhost:9092"
      KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP: "LISTENER_DOCKER_INTERNAL:PLAINTEXT,CONTROLLER:PLAINTEXT,LISTENER_DOCKER_EXTERNAL:PLAINTEXT"
      KAFKA_CFG_INTER_BROKER_LISTENER_NAME: "LISTENER_DOCKER_INTERNAL"
      KAFKA_CFG_SASL_MECHANISM_INTER_BROKER_PROTOCOL: "PLAIN"
      KAFKA_CFG_CONTROLLER_LISTENER_NAMES: "CONTROLLER"
      KAFKA_CFG_SASL_MECHANISM_CONTROLLER_PROTOCOL: "PLAIN"
      KAFKA_CFG_OFFSETS_TOPIC_REPLICATION_FACTOR: "1"
    networks:
      - spot-network-legacy
    volumes:
      - kafka_data_legacy:/bitnami

  spot.broker.new:
    image: docker.io/bitnami/kafka:3.7
    container_name: spot.broker.new
    hostname: spot.broker.new
    restart: "no"
    ports:
      - "9093:9093"
    environment:
      KAFKA_CFG_NODE_ID: 0
      KAFKA_CFG_PROCESS_ROLES: controller,broker
      KAFKA_CFG_CONTROLLER_QUORUM_VOTERS: 0@spot.broker.new:19193
      KAFKA_CFG_LISTENERS: "LISTENER_DOCKER_INTERNAL://:19093,CONTROLLER://:19193,LISTENER_DOCKER_EXTERNAL://:9093"
      KAFKA_CFG_ADVERTISED_LISTENERS: "LISTENER_DOCKER_INTERNAL://spot.broker.new:19093,LISTENER_DOCKER_EXTERNAL://localhost:9093"
      KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP: "LISTENER_DOCKER_INTERNAL:PLAINTEXT,CONTROLLER:PLAINTEXT,LISTENER_DOCKER_EXTERNAL:SASL_PLAINTEXT"
      KAFKA_CFG_INTER_BROKER_LISTENER_NAME: "LISTENER_DOCKER_INTERNAL"
      KAFKA_CFG_SASL_MECHANISM_INTER_BROKER_PROTOCOL: "PLAIN"
      KAFKA_CFG_CONTROLLER_LISTENER_NAMES: "CONTROLLER"
      KAFKA_CFG_SASL_MECHANISM_CONTROLLER_PROTOCOL: "PLAIN"
      KAFKA_CFG_OFFSETS_TOPIC_REPLICATION_FACTOR: "1"
      KAFKA_INTER_BROKER_USER: admin
      KAFKA_INTER_BROKER_PASSWORD: admin
      KAFKA_CLIENT_USERS: spot
      KAFKA_CLIENT_PASSWORDS: spot
    networks:
      - spot-network-new
    volumes:
      - kafka_data_new:/bitnami

  spot.kafka-ui:
    image: provectuslabs/kafka-ui:latest
    container_name: spot.kafka-ui
    restart: "no"
    environment:
      KAFKA_CLUSTERS_0_NAME: spot-legacy
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: spot.broker.legacy:19092
      KAFKA_CLUSTERS_1_NAME: spot-new
      KAFKA_CLUSTERS_1_BOOTSTRAPSERVERS: spot.broker.new:19093
    ports:
      - "8580:8080"
    depends_on:
      - spot.broker.legacy
      - spot.broker.new
    networks:
      - spot-network-legacy
      - spot-network-new

networks:
  spot-network-legacy:
    driver: bridge
  spot-network-new:
    driver: bridge

volumes:
  kafka_data_legacy:
    driver: local
  kafka_data_new:
    driver: local
