version: "3.7"

services:
  spot.zookeeper:
    image: docker.io/bitnami/zookeeper:3.7
    container_name: spot.zookeeper
    restart: "no"
    hostname: spot.zookeeper
    ports:
      - "2282:2181"
    environment:
      ALLOW_ANONYMOUS_LOGIN: "yes"
    networks:
      - spot-network
    volumes:
      - zookeeper_data:/bitnami

  spot.broker:
    image: docker.io/bitnami/kafka:3
    container_name: spot.broker
    hostname: spot.broker
    restart: "no"
    ports:
      - "9092:9092"
    environment:
      KAFKA_CFG_LISTENERS: "LISTENER_DOCKER_INTERNAL://:19092,LISTENER_DOCKER_EXTERNAL://:9092"
      KAFKA_CFG_ADVERTISED_LISTENERS: "LISTENER_DOCKER_INTERNAL://spot.broker:19092,LISTENER_DOCKER_EXTERNAL://localhost:9092"
      KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP: "LISTENER_DOCKER_INTERNAL:PLAINTEXT,LISTENER_DOCKER_EXTERNAL:PLAINTEXT"
      KAFKA_CFG_ZOOKEEPER_CONNECT: "spot.zookeeper:2181"
      KAFKA_CFG_OFFSETS_TOPIC_REPLICATION_FACTOR: "1"
      KAFKA_CFG_PORT: "9092"
      KAFKA_INTER_BROKER_LISTENER_NAME: "LISTENER_DOCKER_INTERNAL"
      ALLOW_PLAINTEXT_LISTENER: "yes"
    depends_on:
      - spot.zookeeper
    networks:
      - spot-network
    volumes:
      - kafka_data:/bitnami

  spot.kafka-ui:
    image: provectuslabs/kafka-ui:latest
    container_name: spot.kafka-ui
    restart: "no"
    environment:
      KAFKA_CLUSTERS_0_NAME: spot
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: spot.broker:19092
      KAFKA_CLUSTERS_0_ZOOKEEPER: spot.zookeeper:2181
    ports:
      - "8580:8080"
    depends_on:
      - spot.zookeeper
      - spot.broker
    networks:
      - spot-network

networks:
  spot-network:
    driver: bridge

volumes:
  zookeeper_data:
    driver: local
  kafka_data:
    driver: local
