# SERVER CONFIGURATION
server:
  port: 8080
  servlet:
    context-path: /spot

# SPRING CONFIGURATION
spring:

# VIRTUAL THREADS CONFIGURATION
  threads:
    virtual:
      enabled: true

# SPRING CLOUD CONFIGURATION
  cloud:
    function:
      definition: orderCreatedListener;orderProcessedListener
    stream:
      kafka:
        binder:
          auto-create-topics: true
        bindings:
          orderCreatedListener-in-0:
            consumer:
              enableDlq: true
              dlqName: order-created-dlt
              autoCommitOnError: true
              autoCommitOffset: true
          orderProcessedListener-in-0:
            consumer:
              enableDlq: true
              dlqName: order-processed-dlt
              autoCommitOnError: true
              autoCommitOffset: true
      bindings:
        orderCreatedProducer-out-0:
          destination: order-created
          binder: order-broker
        orderCreatedListener-in-0:
          destination: order-created
          group: spot
          binder: order-broker
        orderCreatedListener-out-0:
          destination: order-processed
          binder: order-broker
        orderProcessedListener-in-0:
          destination: order-processed
          group: spot
          binder: order-broker
      binders:
        order-broker:
          type: kafka
          environment:
            spring:
              cloud:
                stream:
                  kafka:
                    binder:
                      brokers: localhost:9092
                      configuration:
                        security:
                          protocol: SASL_PLAINTEXT
                        sasl:
                          mechanism: PLAIN
                          jaas:
                            config: "org.apache.kafka.common.security.plain.PlainLoginModule required username=\"spot\" password=\"spot\";"
