server:
  port: 8080
  servlet:
    context-path: /spot

spring:
  cloud:
    stream:
#      function:
#        definition:

      bindings:
        newCreatedProducer-out-0:
          destination: order-created

      kafka:
        binder:
          brokers: localhost:9292
          auto-create-topics: true
