server:
  port: 8080
  servlet:
    context-path: /spot

spring:
  cloud:
    stream:
      function:
        definition: orderCreatedListener;orderProcessedListener

      bindings:
        orderCreatedProducer-out-0:
          destination: order-created
        orderCreatedListener-in-0:
          destination: order-created
          group: spot
        orderCreatedListener-out-0:
          destination: order-processed
        orderProcessedListener-in-0:
          destination: order-processed
          group: spot

      kafka:
        binder:
          brokers: localhost:9292
          auto-create-topics: true
