server:
  port: 8080

spring:
  application:
    name: ${name}
    version: ${version}
  threads:
    virtual:
      enabled: true
  cloud:
    function:
      definition: orderCreatedListener;orderProcessedListener
    stream:
      bindings:
        orderCreatedProducer-out-0:
          destination: order-created
        orderCreatedListener-in-0:
          destination: order-created
          group: spot
        orderCreatedListener-out-0:
          destination: order-processed
        orderProcessedListener-in-0:
          destination: order-processed
          group: spot
      kafka:
        binder:
          brokers: localhost:9092
          auto-create-topics: true
        bindings:
          orderCreatedListener-in-0:
            consumer:
              enableDlq: true
              dlqName: order-created-dlq
              autoCommitOnError: true
              autoCommitOffset: true
          orderProcessedListener-in-0:
            consumer:
              enableDlq: true
              dlqName: order-processed-dlq
              autoCommitOnError: true
              autoCommitOffset: true

# OPEN API CONFIGURATION
springdoc:
  api-docs:
    path: /sync-api-docs
    resolve-schema-properties: true
  override-with-generic-response: false
  paths-to-exclude: /**/api-docs,/swagger-resources/**,/springwolf/**,/async**
  swagger-ui:
    path: /

# ASYNC API CONFIGURATION
springwolf:
  enabled: true
  use-fqn: false
  plugin:
    kafka:
      publishing:
        enabled: true
  paths:
    docs: /async-api-docs
    # Default path: /springwolf/asyncapi-ui.html
    ui: /async-api
  docket:
    base-package: com.cloud.stream.spot
    default-content-type: application/json
    info:
      title: ${name}
      version: ${version}
    servers:
      kafka-server:
        host: localhost:9092
        protocol: kafka